AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
